version: "3.1"

services:
  db:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_DATABASE: 'wcc_geo_distance'
      MYSQL_USER: 'wcc'
      MYSQL_PASSWORD: 'wcc'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3406:3306"
    expose:
      - "3406"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    depends_on:
      - db
    build: .
    ports:
      - "8081:8080"
    expose:
      - "8081"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/wcc_geo_distance?autoReconnect=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "create"
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"

volumes:
  mysql-data: